disable CI step that depends on flakes
Our fork doesn't enable the experimental features by default.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -572,14 +572,15 @@ jobs:
           logger: pretty
       - name: echo $PATH
         run: echo $PATH
-      - name: Test `nix` with `$GITHUB_PATH`
-        if: success() || failure()
-        run: |
-          nix run nixpkgs#hello
-          nix profile install nixpkgs#hello
-          hello
-          nix store gc
-          nix run nixpkgs#hello
+      # We don't enable flakes by default.
+      # - name: Test `nix` with `$GITHUB_PATH`
+      #   if: success() || failure()
+      #   run: |
+      #     nix run nixpkgs#hello
+      #     nix profile install nixpkgs#hello
+      #     hello
+      #     nix store gc
+      #     nix run nixpkgs#hello
       # NOTE(cole-h): GHA pushed a weird image that breaks this test for whatever reason, so ignore
       # the failure for now
       - name: Test bash
